title: "Benchmarks for Reasoning Shortcuts: When Machine Learning Concepts Go Astray"
author: Samuele Bortolotti
email: samuele.bortolotti@unitn.it
description: >- # this means to ignore newlines until "baseurl:"
  "Benchmarks for Reasoning Shortcuts: When Machine Learning Concepts Go Astray" benchmark paper
baseurl: "/rsbenc" # the subpath of your site, e.g. /blog
github_username: samuelebortolotti
repository: unitn-sml/rsbenc

# Build settings
encoding: UTF-8
plugins:
  - jekyll-seo-tag

# Default language
include: [en]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
